### ISSUE TITLE
Create the hostapp bootloader update hooks

### ISSUE THREAD

**Issue by floion** [resin-os/resin-jetson-tx2#35]
Currently the Jetson TX2 is missing the bootloader update hooks that are called by the hostapps updater when doing a host OS update.

**Comment by floion** [comment]
@telphan please reference these hooks here and close this item if you feel it is handled

**Comment by imrehg** [comment]
This has now been deployed, right, @telphan ? (in 2.9.7+rev2)

**Comment by floion** [comment]
ping @telphan ^

**Comment by telphan** [comment]
https://github.com/resin-os/resin-jetson-tx2/blob/master/layers/meta-resin-jetson/recipes-support/hostapp-update-hooks
