### ISSUE TITLE
usb_modeswitch fails with core dump

### ISSUE THREAD

**Issue by spanceac** [resin-os/resin-jetson-tx2#94]
No modem work on the Jetson TX2 board because usb_modeswitch fails with core dump.

```Oct 25 07:59:22 6f166e9 usb_modeswitch_dispatcher[1376]: usb_modeswitch_dispatcher: malloc.c:2415: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE &&prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Oct 25 07:59:22 6f166e9 systemd[1]: usb_modeswitch@1-2:1.0.service: Main process exited, code=dumped, status=6/ABRT
Oct 25 07:59:22 6f166e9 systemd[1]: usb_modeswitch@1-2:1.0.service: Unit entered failed state.
Oct 25 07:59:22 6f166e9 systemd[1]: usb_modeswitch@1-2:1.0.service: Failed with result 'core-dump'.```

**Comment by floion** [comment]
https://github.com/resin-os/resin-jetson-tx2/pull/95
